# HyperRAM Configuration
clk_freq: 50000000
vendor: xilinx          # lattice or xilinx
device: "xc7a35t"       # Target device part number
toolchain: "vivado"     # toolchain: vivado, diamond, or trellis (for Lattice)
